# Generated by Django 3.1.5 on 2021-01-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='contents',
            new_name='preview',
        ),
        migrations.AddField(
            model_name='news',
            name='writer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
