# Generated by Django 3.1.5 on 2021-01-29 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210127_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('writer', models.CharField(blank=True, max_length=50, null=True)),
                ('preview', models.TextField()),
            ],
            options={
                'verbose_name': 'it_new',
                'verbose_name_plural': 'it_news',
                'db_table': 'it_news',
            },
        ),
        migrations.CreateModel(
            name='WorldNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('writer', models.CharField(blank=True, max_length=50, null=True)),
                ('preview', models.TextField()),
            ],
            options={
                'verbose_name': 'world_new',
                'verbose_name_plural': 'world_news',
                'db_table': 'world_news',
            },
        ),
        migrations.RenameModel(
            old_name='News',
            new_name='EconomicsNews',
        ),
        migrations.AlterModelOptions(
            name='economicsnews',
            options={'verbose_name': 'economics_new', 'verbose_name_plural': 'economics_news'},
        ),
        migrations.AlterModelTable(
            name='economicsnews',
            table='economics_news',
        ),
    ]
