# Generated by Django 3.1.5 on 2021-01-29 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210129_1056'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EconomicsNews',
        ),
        migrations.DeleteModel(
            name='WorldNews',
        ),
        migrations.AlterModelOptions(
            name='itnews',
            options={},
        ),
        migrations.AlterModelTable(
            name='itnews',
            table=None,
        ),
    ]
